services:
  frontend:
    container_name: lend-my-skill-frontend
    build:
      context: apps/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - lend-my-skill
    ports:
      - 3000:3000

  backend:
    container_name: lend-my-skill-backend
    env_file:
      - .env
    build:
      context: apps/backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - lend-my-skill
    ports:
      - 5000:5000

networks:
  lend-my-skill:

