services:
  frontend:
    container_name: lend-my-skill-frontend
    build:
      context: apps/frontend
      dockerfile: Dockerfile
    env_file:
      - apps/frontend/.env.production
    networks:
      - lend-my-skill
    ports:
      - 3000:3000
    

networks:
  lend-my-skill:
