
name: Run Analyze

on:
  push:
    branches:
      - main
      - apps

jobs:
  lint:
    name: Run Analyze
    runs-on: windows-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      
      - name: Install Packages
        run:  cd packages/mobile/components; flutter pub get; cd ../controllers; flutter pub get; cd ../services; flutter pub get; cd ../../../ ; cd apps/mobile/freelancer; flutter pub get; cd ../client; flutter pub get;
      
      - name: Install Melos
        run: dart pub global activate melos

      - name: Run Melos
        run: melos analyze
      
      