name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - backend-refactor

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Go to Docs Folder
        run: cd apps/docs

      - name: Setup Corepack
        run: corepack prepare
      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm build
      - name: Export Website
        run: pnpm export
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./out
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
