name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Go to Docs Folder
        run: cd apps/docs

      - name: Setup Pnpm
        run: npm i -g pnpm@latest
      - name: Install dependencies
        run: cd apps/docs && pnpm install
      - name: Build website
        run: cd apps/docs && pnpm build
      - name: Export Website
        run: cd apps/docs && pnpm export
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./apps/docs/out
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com