name: Run Lint

on:
  push:
    branches:
      - main

jobs:
  frontend_linter:
    name: Run Linter for frontend
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Setting Up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Pnpm
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lint
        run: cd apps/frontend && pnpm lint
  backend_linter:
    name: Run linter for Backend
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Setting Up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Pnpm
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lint
        run: cd apps/backend && pnpm lint
