import "./globals.css";
import { Noto_Sans, Work_Sans } from "next/font/google";
import { clsx } from "clsx";
import { Toaster } from "react-hot-toast";

export const notoSans = Work_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          notoSans.className,
          "bg-brand-light-primary",
          "text-brand-light-text"
        )}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
